name: build
on:
  push:
    branches:
      - master
    tags:
      - v*
permissions:
  contents: write
  packages: write
jobs:
  test:
    uses: greboid/.github/.github/workflows/go-test.yml@master
    secrets: inherit
  container:
    uses: greboid/.github/.github/workflows/docker.yml@master
    secrets: inherit
    needs: [test]
  release:
    if: github.ref_type == 'tag'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - run: CGO_ENABLED=0 go build -tags netgo,opusergo -a -trimpath -ldflags='-w -extldflags "-static" -buildid=' -o adze .
      - uses: softprops/action-gh-release@v2
        with:
          files: adze
